"use client";

import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { Provider } from "react-redux";
import store from "@/store";

const inter = Nunito_Sans({ subsets: ["latin"] });

const metadata = {
  title: "Woorkroom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>{ metadata.title }</title>
      <body className={inter.className}>
        <Provider store={store}>
          {children}
        </Provider>
      </body>
    </html>
  );
}
