"use client";

import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { Provider } from "react-redux";
import store from "@/store";
import { LynchpinProvider } from "@/helpers/lynchpinValidator";

const inter = Nunito_Sans({ subsets: ["latin"] });

const metadata = {
  title: "Woorkroom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/logo.png" />
      </head>
      <body className={inter.className}>
        <Provider store={store}>
          <LynchpinProvider>
            {children}
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar
              newestOnTop={false}
              closeOnClick={false}
              rtl={false}
              pauseOnFocusLoss
              draggable={false}
              pauseOnHover
              theme="colored"
            />
          </LynchpinProvider>
        </Provider>
      </body>
    </html>
  );
}
